[workspace]
git_release_enable = true
dependencies_update = false # TODO: re-enable when `cargo update` works in this project
pr_per_package = true
git_only = true

git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""
